version: '3.8'

services:
  crawler:
    build:
      context: .
      args:
        SWOOLE_VERSION: 5.0.3
        COMPOSER_VERSION: 2.6.5
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G