services:
  crawler:
    container_name: hyperf-crawler
    build:
      context: .
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G